version: '3'

services:
  cupoch:
    image: cupoch:latest
    build: .
    container_name: cupoch
    environment:
      - "DISPLAY=${DISPLAY}"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
